/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * interfaz.java
 *
 * Created on 31-may-2012, 11:08:37
 */
package jess;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author flavio
 */
public class interfaz extends javax.swing.JFrame {

    ConsolePanel c;

    /** Creates new form interfaz */
    public interfaz(ConsolePanel c) {
        initComponents();
        this.c = c;
        this.add(c, BorderLayout.CENTER);
//        JPanel j = new JPanel();
//        j.setLayout(new BorderLayout());
//        j.add(c, BorderLayout.CENTER);
//        jScrollPane1.getViewport().setView(j);
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
